### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by mahlaranjeet** [CamaraLab/CAJAL#13]
(base) rmahla_admin@KIRMAC201 OMICS365 % conda create --name CAJAL python=3.9.17
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Applications/anaconda3/envs/CAJAL

  added / updated specs:
    - python=3.9.17

The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/osx-64::ca-certificates-2023.05.30-hecd8cb5_0 
  libcxx             pkgs/main/osx-64::libcxx-14.0.6-h9765a3e_0 
  libffi             pkgs/main/osx-64::libffi-3.4.4-hecd8cb5_0 
  ncurses            pkgs/main/osx-64::ncurses-6.4-hcec6c5f_0 
  openssl            pkgs/main/osx-64::openssl-3.0.9-hca72f7f_0 
  pip                pkgs/main/osx-64::pip-23.1.2-py39hecd8cb5_0 
  python             pkgs/main/osx-64::python-3.9.17-h5ee71fb_0 
  readline           pkgs/main/osx-64::readline-8.2-hca72f7f_0 
  setuptools         pkgs/main/osx-64::setuptools-67.8.0-py39hecd8cb5_0 
  sqlite             pkgs/main/osx-64::sqlite-3.41.2-h6c40b1e_0 
  tk                 pkgs/main/osx-64::tk-8.6.12-h5d9f67b_0 
  tzdata             pkgs/main/noarch::tzdata-2023c-h04d1e81_0 
  wheel              pkgs/main/osx-64::wheel-0.38.4-py39hecd8cb5_0 
  xz                 pkgs/main/osx-64::xz-5.4.2-h6c40b1e_0 
  zlib               pkgs/main/osx-64::zlib-1.2.13-h4dc903c_0 

Proceed ([y]/n)? y

Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate CAJAL
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) rmahla_admin@KIRMAC201 OMICS365 % conda activate CAJAL
(CAJAL) rmahla_admin@KIRMAC201 OMICS365 % pip install git+https://github.com/CamaraLab/CAJAL.git
Collecting git+https://github.com/CamaraLab/CAJAL.git
  Cloning https://github.com/CamaraLab/CAJAL.git to /private/var/folders/wd/0cjqfxsd7zjc3gx989xp40980000gt/T/pip-req-build-jmijks7m
  Running command git clone --filter=blob:none --quiet https://github.com/CamaraLab/CAJAL.git /private/var/folders/wd/0cjqfxsd7zjc3gx989xp40980000gt/T/pip-req-build-jmijks7m
  Resolved https://github.com/CamaraLab/CAJAL.git to commit 385f5fa4a1782f95b260e0cb981335b19af2c839
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting igraph (from cajal==0.2.0)
  Using cached igraph-0.10.6-cp39-abi3-macosx_10_9_x86_64.whl (1.9 MB)
Collecting leidenalg (from cajal==0.2.0)
  Using cached leidenalg-0.10.0-cp39-cp39-macosx_10_9_x86_64.whl (1.7 MB)
Collecting networkx~=2.8.8 (from cajal==0.2.0)
  Using cached networkx-2.8.8-py3-none-any.whl (2.0 MB)
Collecting numpy (from cajal==0.2.0)
  Using cached numpy-1.25.1-cp39-cp39-macosx_10_9_x86_64.whl (20.1 MB)
Collecting cython>=0.23 (from cajal==0.2.0)
  Using cached Cython-0.29.36-py2.py3-none-any.whl (988 kB)
Collecting pathos (from cajal==0.2.0)
  Using cached pathos-0.3.0-py3-none-any.whl (79 kB)
Collecting pot>=0.9.0 (from cajal==0.2.0)
  Using cached POT-0.9.0-cp39-cp39-macosx_10_9_x86_64.whl (233 kB)
Collecting potpourri3d (from cajal==0.2.0)
  Using cached potpourri3d-0.0.8-cp39-cp39-macosx_10_9_x86_64.whl (843 kB)
Collecting python-louvain (from cajal==0.2.0)
  Using cached python-louvain-0.16.tar.gz (204 kB)
  Preparing metadata (setup.py) ... done
Collecting scipy (from cajal==0.2.0)
  Using cached scipy-1.11.1-cp39-cp39-macosx_10_9_x86_64.whl (37.2 MB)
Collecting scikit-image (from cajal==0.2.0)
  Using cached scikit_image-0.21.0-cp39-cp39-macosx_10_9_x86_64.whl (13.0 MB)
Collecting tifffile (from cajal==0.2.0)
  Using cached tifffile-2023.7.10-py3-none-any.whl (220 kB)
Collecting trimesh (from cajal==0.2.0)
  Using cached trimesh-3.22.4-py3-none-any.whl (682 kB)
Collecting umap-learn~=0.5.3 (from cajal==0.2.0)
  Using cached umap_learn-0.5.3-py3-none-any.whl
INFO: pip is looking at multiple versions of cajal to determine which version is compatible with other requirements. This could take a while.
ERROR: Package 'cajal' requires a different Python: 3.9.17 not in '~=3.10'
(CAJAL) rmahla_admin@KIRMAC201 OMICS365 %

**Comment by patrick-nicodemus** [comment]
Thank you for this bug report. We plan to release the next version of CAJAL within the next few days with support for Python 3.9 and we encourage you to check it out and report any errors you may find!

**Comment by patrick-nicodemus** [comment]
@mahlaranjeet We have released a new version of CAJAL which should be compatible with Python 3.9! Please let us know if you have any difficulty installing it. Thank you!
