### ISSUE TITLE
Multiprocessing issue due to dill's recurse=True

### ISSUE THREAD

**Issue by schlegelp** [CamaraLab/CAJAL#18]
Hi. I came across a weird issue when importing CAJAL and then using multiprocessing in NAVis.

This works:
```python
import navis 
import cajal

# Dispatch some work using pathos/multiprocessing pool
navis.prune_twigs(navis.example_neurons(3), size=5000/8, parallel=True)
```

This breaks with `RecursionError: maximum recursion depth exceeded in comparison`
```python
import navis 
import cajal.swc

# Dispatch some work using pathos/multiprocessing pool
navis.prune_twigs(navis.example_neurons(3), size=5000/8, parallel=True)
```

I tracked it down to [this line](https://github.com/CamaraLab/CAJAL/blob/2e350815ed18007bb22b56b11bc1029a64ba74dc/src/cajal/swc.py#L24) in `swc.py`:
```python
dill.settings["recurse"] = True
```

Multiprocessing is opaque at the best of times so not sure what to do about it - just thought I'd leave a breadcrumb that this might cause breakage in other libraries. If you need that flag, perhaps you could set and unset using a context manager?

On my end, I might add a warning to NAVis when that flag is set to give users the chance set to False manually.

**Comment by patrick-nicodemus** [comment]
@schlegelp Just wanted to let you know I saw this and will address it when I have time. I may remove dill and use the standard Python multiprocessing library, as in spite of its additional flexibility it has resulted in difficulties which we haven't found workarounds for, discussed here. https://github.com/uqfoundation/pathos/issues/111#top

**Comment by patrick-nicodemus** [comment]
Recursion removed by https://github.com/CamaraLab/CAJAL/commit/b6228d4371f778bb2d9ae935b782a807e88c7694
